version: "3.8"

services:
  web:
    build:
      context: backend
      dockerfile: Dockerfile
    user: $UID:$GID
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
    container_name: web
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: db

  front:
    image: marcelocg/nextjs
    ports:
      - 3000:3000
    volumes:
      - ./front:/srv/app
    container_name: front

volumes:
  postgres_data:
